CDD/CDD/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('',include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

CDD/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('',home,name='home'),
    path('register/',register,name='register'),
    path('login/',user_login,name='login'),
    path('logout/', logout_view, name='logout'),
    path('upload/', upload, name='upload'),
    path('type/', type, name='plant_type'),
    path('board/', board, name='dashboard'),
    path('upload_image/', upload_image, name='upload_image'),
    path('croprec/', Crop_Recommendation, name='crop_rec'),
    path('fertrec/', Fertilizer_Recommendation, name='fert_rec'),
    path('pestrec/<int:Did>/', pest_rec, name='pest_rec'),
]

CDD/templates/dashbord.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Disease Detection</title>

        <!-- CSS FILES -->        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap" rel="stylesheet">
                        
        <link href="/media/css/bootstrap.min.css" rel="stylesheet">

        <link href="/media/css/bootstrap-icons.css" rel="stylesheet">

        <link href="/media/css/templatemo-topic-listing.css" rel="stylesheet">

        <link href="/media/css/style.css" rel="stylesheet">

        <script src="/media/js/script.js"></script>

    </head>
    
    <body id="top">

        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'accounts:home' %}">
                        <i class="bi-back"></i>
                        <span>CDD</span>
                    </a>

                    <div class="d-lg-none ms-auto me-4">
                        <a href="#top" class="navbar-icon bi-person smoothscroll"></a>
                    </div>
    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
    
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ms-lg-5 me-lg-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
                            </li>

                            
                        </ul>

                        <div class="col-lg-3 col-md-4 col-12 mt-4 mt-lg-0 ms-auto"  style="padding-left: 20%;">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle bi-person" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                </button>
    
                                <ul class="dropdown-menu">
                                    {% csrf_token %}
                                                                       <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:login' %}"><button class="dropdown-item" type="button">Login</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Login</button>
  {% endif %}
</li>

                                    <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:register' %}"><button class="dropdown-item" type="button">Register</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Register</button>
  {% endif %}
</li>
                                    <li>
    {% if  user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}"><button class="dropdown-item" type="button">Logout</button></a>
    {% else %}
    <button class="dropdown-item" type="button" disabled >Logout</button></a>
    {% endif %}
</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            
            
            <section class="hero-section d-flex justify-content-center align-items-center min-vh-100" id="section_1" style=" padding-bottom: 0%; padding-top: 40px; width: 100%;">
                <div class="container ">
                    <div class="row mt-5 justify-content-center">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h3>User</h3>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="username">Username:</label>
                                        <p id="username">{{ user.first_name }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email:</label>
                                        <p id="email">{{ user.email }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3 justify-content-center" style="width: 980px;padding-left:340px;">
                    <section class="bg-light py-4 card justify-content-center align-items-center" style=" padding-top: 5%; width:100%; ">
                        <div class="container justify-content-center align-items-center">
                            <table class="table mt-3 justify-content-center">
                              <thead>
                                <tr>
                                  <th scope="col">Crop Image</th>
                                  <th scope="col">Disease</th>
                                </tr>
                              </thead>
                              <tbody>
                              {% for disease in diseases %}

                                <tr>
                                  <td><a href="{% url 'accounts:pest_rec' disease.id %}"><img src="{{ disease.image.image.url }}" alt="{{ disease.image.image.name }}" style="width: 100px; height: 100px;"></a></td>
                                  <td><a href="{% url 'accounts:pest_rec' disease.id %}">{{ disease.disease }}</a></td>
                                </tr>

                              {% endfor %}
                                <!-- Add more rows as needed -->
                              </tbody>
                            </table>
                          </div>
                      </section>
                    </div>
                </div>
                
            </section>

            
            
        </main>



        <!-- JAVASCRIPT FILES -->
        <script src="/media/js/jquery.min.js"></script>
        <script src="/media/js/bootstrap.bundle.min.js"></script>
        <script src="/media/js/jquery.sticky.js"></script>
        <script src="/media/js/click-scroll.js"></script>
        <script src="/media/js/custom.js"></script>

    </body>
</html>

CDD/templates/plant_type.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Topic Listing Page</title>

        <!-- CSS FILES -->        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap" rel="stylesheet">
                        
        <link href="/media/css/bootstrap.min.css" rel="stylesheet">

        <link href="/media/css/bootstrap-icons.css" rel="stylesheet">

        <link href="/media/css/templatemo-topic-listing.css" rel="stylesheet">

    </head>
    
    <body class="topics-listing-page" id="top">

        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'accounts:home' %}">
                        <i class="bi-back"></i>
                        <span>CDD</span>
                    </a>

                    <div class="d-lg-none ms-auto me-4">
                        <a href="#top" class="navbar-icon bi-person smoothscroll"></a>
                    </div>
    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
    
                    <div class="collapse navbar-collapse justify-content-center align-items-center " id="navbarNav" >
                        <ul class="navbar-nav ms-lg- me-lg-auto"> 
                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="{% url 'accounts:home' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="{% url 'accounts:dashboard' %}">Dashboard</a>
                            </li>
                            
                        </ul>

                        <div class="col-lg-3 col-md-4 col-12 mt-4 mt-lg-0 ms-auto" style="padding-left: 20%;">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle bi-person" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                </button>
    
                                <ul class="dropdown-menu">
                                    {% csrf_token %}
                                                                       <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:login' %}"><button class="dropdown-item" type="button">Login</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Login</button>
  {% endif %}
</li>

                                    <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:register' %}"><button class="dropdown-item" type="button">Register</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Register</button>
  {% endif %}
</li>
                                    <li>
    {% if  user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}"><button class="dropdown-item" type="button">Logout</button></a>
    {% else %}
    <button class="dropdown-item" type="button" disabled >Logout</button></a>
    {% endif %}
</li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </nav>


            <header class="site-header d-flex flex-column justify-content-center align-items-center">
                <div class="container">
                    <div class="row align-items-center">

                        <div class="col-lg-5 col-12">
                            <nav aria-label="breadcrumb">
                            
                            </nav>

                            <h2 class="text-white">Choose The Crop</h2>
                        </div>

                    </div>
                </div>
            </header>


            <section class="section-padding">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-8 col-12 mt-3 mx-auto hidden">
                            <div class="custom-block custom-block-topics-listing bg-white shadow-lg mb-5 ">
                                <div class="d-flex">
                                    <img src="/media/images/tomato.jpg" class="custom-block-image img-fluid" alt="">

                                    <div class="custom-block-topics-listing-info d-flex">
                                        <div>
                                            <h5 class="mb-2">tomato</h5>

                                            <p class="mb-0">Upload the diseased image of tomato <br>get the diseas name  </p>

                                            <a href="{% url 'accounts:upload' %}" class="btn custom-btn mt-3 mt-lg-4">Learn More</a>
                                        </div>

                                        
                                    </div>
                                </div>
                            </div>

                            <div class="custom-block custom-block-topics-listing bg-white shadow-lg mb-5 ">
                                <div class="d-flex">
                                    <img src="/media/images/corn.jpg" class="custom-block-image img-fluid" alt="">

                                    <div class="custom-block-topics-listing-info d-flex">
                                        <div>
                                            <h5 class="mb-2">Corn</h5>

                                            <p class="mb-0">Upload the diseased image of corn <br>get the diseas name  </p>

                                            <a href="{% url 'accounts:upload' %}" class="btn custom-btn mt-3 mt-lg-4">Learn More</a>
                                        </div>

                                        
                                    </div>
                                </div>
                            </div>

                            <div class="custom-block custom-block-topics-listing bg-white shadow-lg mb-5 ">
                                <div class="d-flex">
                                    <img src="/media/images/potato.jpg" class="custom-block-image img-fluid" alt="">

                                    <div class="custom-block-topics-listing-info d-flex">
                                        <div>
                                            <h5 class="mb-2">Potato</h5>

                                            <p class="mb-0">Upload the diseased image of potato <br>get the diseas name </p>

                                            <a href="{% url 'accounts:upload' %}" class="btn custom-btn mt-3 mt-lg-4">Learn More</a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        
        </main>

		<footer class="site-footer section-padding">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-12 mb-4 pb-2">
                        <a class="navbar-brand mb-2" href="index.html">
                            <i class="bi-back"></i>
                            <span>Topic</span>
                        </a>
                    </div>

                    <div class="col-lg-3 col-md-4 col-6">
                        <h6 class="site-footer-title mb-3">Resources</h6>

                        <ul class="site-footer-links">
                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Home</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">How it works</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">FAQs</a>
                            </li>

                            <li class="site-footer-link-item">
                                <a href="#" class="site-footer-link">Contact</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-4 col-6 mb-4 mb-lg-0">
                        <h6 class="site-footer-title mb-3">Information</h6>

                        <p class="text-white d-flex mb-1">
                            <a href="tel: 305-240-9671" class="site-footer-link">
                                305-240-9671
                            </a>
                        </p>

                        <p class="text-white d-flex">
                            <a href="mailto:info@company.com" class="site-footer-link">
                                info@company.com
                            </a>
                        </p>
                    </div>

                    <div class="col-lg-3 col-md-4 col-12 mt-4 mt-lg-0 ms-auto">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            English</button>

                            <ul class="dropdown-menu">
                                <li><button class="dropdown-item" type="button">Thai</button></li>

                                <li><button class="dropdown-item" type="button">Myanmar</button></li>

                                <li><button class="dropdown-item" type="button">Arabic</button></li>
                            </ul>
                        </div>

                        <p class="copyright-text mt-lg-5 mt-4">Copyright © 2048 Topic Listing Center. All rights reserved.
                        <br><br>Design: <a rel="nofollow" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
                        
                    </div>

                </div>
            </div>
        </footer>

        <!-- JAVASCRIPT FILES -->
        <script src="/media/js/jquery.min.js"></script>
        <script src="/media/js/bootstrap.bundle.min.js"></script>
        <script src="/media/js/jquery.sticky.js"></script>
        <script src="/media/js/custom.js"></script>

    </body>
</html>

CDD/templates/upload.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Crop Disease Detection</title>

    <!-- CSS FILES -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap"
        rel="stylesheet">

    <link href="/media/css/bootstrap.min.css" rel="stylesheet">

    <link href="/media/css/bootstrap-icons.css" rel="stylesheet">

    <link href="/media/css/templatemo-topic-listing.css" rel="stylesheet">

    <link href="/media/css/style.css" rel="stylesheet">

    <script src="js/script.js"></script>

</head>

<body id="top">

    <main>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'accounts:home' %}">
                    <i class="bi-back"></i>
                    <span>CDD</span>
                </a>

                <div class="d-lg-none ms-auto me-4">
                    <a href="#top" class="navbar-icon bi-person smoothscroll"></a>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-lg-5 me-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:dashboard' %}">dashbord</a>
                        </li>

                    </ul>

                    <div class="col-lg-3 col-md-4 col-12 mt-4 mt-lg-0 ms-auto" style="padding-left: 20%;">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle bi-person" type="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            </button>

                            <ul class="dropdown-menu">
                                {% csrf_token %}
                                <li>
                                    {% if not user.is_authenticated %}
                                    <a href="{% url 'accounts:login' %}"><button class="dropdown-item"
                                            type="button">Login</button></a>
                                    {% else %}
                                    <button class="dropdown-item disabled" type="button" disabled>Login</button>
                                    {% endif %}
                                </li>

                                <li>
                                    {% if not user.is_authenticated %}
                                    <a href="{% url 'accounts:register' %}"><button class="dropdown-item"
                                            type="button">Register</button></a>
                                    {% else %}
                                    <button class="dropdown-item disabled" type="button" disabled>Register</button>
                                    {% endif %}
                                </li>
                                <li>
                                    {% if user.is_authenticated %}
                                    <a href="{% url 'accounts:logout' %}"><button class="dropdown-item"
                                            type="button">Logout</button></a>
                                    {% else %}
                                    <button class="dropdown-item" type="button" disabled>Logout</button></a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>


        <section class="hero-section d-flex justify-content-center align-items-center " id="section_1"
            style="padding-top: 10%; padding-bottom: 20%;">

            <body>
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-body  mb-3">
                                    <h5 class="card-title">Upload The leaf Image </h5>
                                    <form method="post" enctype="multipart/form-data"
                                        action="{% url 'accounts:upload_image' %}">
                                        {% csrf_token %}
                                        <!--                                  <div class="row justify-content-center"> <h3> {{ predicted_disease }} </h3>-->
                                        <!--                                  </div>-->
                                        <div class="form-group  mb-3">
                                            <label for="file"></label>
                                            {% csrf_token %}
                                            {{ form.as_p }}


                                    </form>



                                    <button type="submit"
                                        class="btn custom-btn mt-3 mt-lg-4 btn-primary ">Upload</button>
                                </div>
                                <div class="row justify-content-center">
                                    <div class="col-md-6">

                                        <div class="row justify-content-center">
                                            <img src="{{ url }}" >

                                        </div>
                                        <div class="form-group  mb-3">
                                        </div>
                                    </div>
                                    <div>
                                        <h3 style="text-align:center"> {{ predicted_disease }} </h3>
                                    </div>
                                </div>
                            </div>

                            <script>
                                document.getElementById('file').addEventListener('change', function () {
                                    const file = this.files[0];
                                    if (file) {
                                        const reader = new FileReader();
                                        reader.onload = function (event) {
                                            document.getElementById('preview').src = event.target.result;
                                            document.getElementById('preview').style.display = 'block';
                                        }
                                        reader.readAsDataURL(file);
                                    } else {
                                        document.getElementById('preview').src = '#';
                                        document.getElementById('preview').style.display = 'none';
                                    }
                                });
                            </script>
        </section>
    </main>



    <!-- JAVASCRIPT FILES -->
    <script src="/media/js/jquery.min.js"></script>
    <script src="/media/js/bootstrap.bundle.min.js"></script>
    <script src="/media/js/jquery.sticky.js"></script>
    <script src="/media/js/click-scroll.js"></script>
    <script src="/media/js/custom.js"></script>

</body>

</html>